"""empty message

Revision ID: 8b039930cfd1
Revises: b63f71764420
Create Date: 2024-06-18 16:38:00.429786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b039930cfd1'
down_revision = 'b63f71764420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binaural', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('track_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('date_publication',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binaural', schema=None) as batch_op:
        batch_op.alter_column('date_publication',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('track_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
